### ISSUE TITLE
Endpoint para registrar un movimiento de producto

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p3_g8_sf#17]
**Endpoint para registrar un movimiento de producto**:

* **Requerimiento**: Crear un endpoint que permita registrar un nuevo movimiento de producto (compra, venta, transferencia, ajuste).
* **Detalles**:
  * Método: `POST`
  * URL: `/api/movimientos`
  * Cuerpo de la solicitud: Detalles del movimiento, incluyendo `tipoMovimiento`, `categoriaId`, `productoId`, `cantidad`, `empleadoId`, `proveedorId`, `fecha`, `hora`, `descripcion`, `precio_unitario`, `factura`.
  * Respuesta: Detalles del movimiento creado, incluyendo `id`, `cantidad_antes`, `cantidad_despues`.
  * Requisitos funcionales:
    * Validar que todos los IDs proporcionados existen.
    * Actualizar las cantidades de productos antes y después del movimiento.
    * Manejar transacciones de compra y venta adecuadamente.

**Comment by FedericoDInocencio** [comment]
hice cambios en el controlador
